version: '3'
services:
  app:
    build: .
    command: yarn dev
    ports:
      - '3009:3009'
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
